Feature html forms
Emmanuelaaron/HTML-forms pull request #1
Opened 2020-01-28 21:45 UTC by Emmanuelaaron

2020-01-28 22:27 UTC, mosesogwo commented on index.html
> +            <!-- <p>Invisible reCAPTCHA by Google Privacy Policy and Terms of Use.</p> -->
Remove commented code

2020-01-28 22:27 UTC, mosesogwo requested changes
**Hi @Emmanuelaaron :clap: Nice job. A few changes and you can :rocket:**

1. In your form, the `type` attribute for the phone field should be `tel`, not `number`.

2. Your form should be enclosed in `<form>` tags.

3. Package-lock.json is not required for this project. Remove it from the project folder.

4. Remove commented code from your html. (See my comment on index.html)

5. Please, set your footer in order. It should be centralized and the button on the right shouldn't be ther.

![image](https://user-images.githubusercontent.com/46611870/73310784-41008e00-4225-11ea-87ea-03562699ad5b.png)

**Why has this project been done in only two commits?**

_**Kindly make these changes and submit another code review request.**_

**Good luck:smile:**

2020-01-29 02:18 UTC, MauricioRobayo requested changes
Hi!

Well done fixing the issues previously pointed out, the project meets all the requirements, but... the [HTML validation is not passing](https://validator.w3.org/nu/?doc=https%3A%2F%2Femmanuelaaron.github.io%2FHTML-forms%2F) 😥:

- [ ] Fix HTML validation error.

[OPTIONAL]: You can add a `for` attribute to the labels to associate them with their corresponding input,, take a look at the label [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label).

Status: **Request changes**.

2020-01-29 07:16 UTC, kobiyoyo commented
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

2020-01-29 07:19 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap:

2020-01-29 07:24 UTC, merged